{{- range .Values.middlewares }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  {{- toYaml .spec | nindent 2 }}
{{- end }}